### ISSUE TITLE
Scan for raspi/hub

### ISSUE THREAD

**Issue by joscormir** [joscormir/domocracy#25]
Avahi

**Comment by Bardo91** [comment]
Raspi has AVAHI to broadcast the service (https://github.com/joscormir/domocracy/wiki/Configure-AVAHI-on-Raspbian) but Android cant find it

**Comment by Bardo91** [comment]
Works properly under the same network (Mask 255.255.255.0) both AVAHI in raspi and "HubFinder" in android
