### ISSUE TITLE
Kodi infinite loop

### ISSUE THREAD

**Issue by joscormir** [joscormir/domocracy#3]
In KodiLastShowPanel.java when you have not Kodi in your Computer there is a while loop with the variable hasTvShowList that is gonna be always empty. Need to fix that in the app.
Proposal:
Break the while loop after two or three tries
![issuekodiinfiniteloop](https://cloud.githubusercontent.com/assets/5664515/6503527/43563ed2-c32e-11e4-9167-b0c94420ae9b.png)

**Comment by Bardo91** [comment]
Solved.
