### ISSUE TITLE
Unknown crash with android's request of last episode in hub

### ISSUE THREAD

**Issue by Bardo91** [joscormir/domocracy#69]
The hub app crashes while testing in android lastTvShowPanel.

![LastScreen](https://cloud.githubusercontent.com/assets/3602335/6664063/b5bac3de-cbcc-11e4-9cf1-642c29da0fa4.png)

**Comment by Bardo91** [comment]
The error is caused by an incomplete request from the android app. Check incomplete requests in hub to avoid this errors

**Comment by technik** [comment]
Can't reproduce
